### ISSUE TITLE
Using with NodeJS

### ISSUE THREAD

**Issue by nahakiole** [i4mi/fhir-resources-r4#14]
Not working in NodeJS because NodeJS doesn't support XMLHttpRequest and has to be installed manually and included in the global namespace to work.

Could you update this to make it work with NodeJS?

**Comment by heg2** [comment]
I guess this is an issue for https://github.com/i4mi/fhir-wrappers.ts, probably the web wrapper?

**Comment by nahakiole** [comment]
It could probably be solved by adding xmlhttprequest (https://www.npmjs.com/package/xmlhttprequest) to the dependencies which is a wrapper to use xmlhttprequest in nodejs. 

Then using require("xmlhttprequest").XMLHttpRequest to get the library in the appropriate place probably somewhere around https://github.com/i4mi/fhir-resources-r4/blob/master/src/apiMethods/apiMethods.ts#L218

**Comment by ies1** [comment]
yes, i'll add the xmlhhtprequest from npm and import it in the api file. 
BUT: I'll implement a check if the global.XmlHttpRequest is undefined and then use the package. If the global is already defined from a browser, it should use the global one.
