### ISSUE TITLE
Typo? in QuestionnaireItemType

### ISSUE THREAD

**Issue by stefarr** [i4mi/fhir-resources-r4#17]

**Comment by stefarr** [comment]
export declare enum QuestionnaireItemType {
    ...
    OPEN_CHOICE = "open-choise"
    ...
}

**Comment by isels1** [comment]
yes, you are right. It should be open-choice according the difinition http://hl7.org/fhir/valueset-item-type.html

Thx for reporting.

**Comment by heg2** [comment]
This is fixed in version 1.0.10.
