### ISSUE TITLE
SampledData.dimensions positiveInt type

### ISSUE THREAD

**Issue by alex-fahrni-i4mi** [i4mi/fhir-resources-r4#29]
The type of the "dimensions" property on the "SampleData" interface is set to "positiveInt".

"positiveInt" is declared as an alias for "string". This results in the "dimensions" property being encoded as "string" when a "SampleData" object is converted to json. This causes the validation of the fhir resource to fail.

I haven't tested this, but I imagine the problem occurs wherever "positiveInt" is used, as well as for other integer types that have been defined as "string".

**Comment by heg2** [comment]
This is actually also an issue for the fhir generator, i created an issue in Gitlab.

**Comment by heg2** [comment]
This is in version 2.0.0
